# application.properties와 yml중 하나를 선택해서 사용
# 두 개 같이 사용시 properties를 읽어드림

# yml, 또는 yaml이 좋은 이유
# 1. 한글 작성이 용이하다.(추가 인코딩 필요 X)
# 2. 들어쓰기 및 동일한 키 값이 중보되지 않아 가독성이 좋음
# 3. 주석을 # 하나로 사용하기 그나마 용이(들여쓰기로 인해 코드를 주석화해도 어떤 것이 주석이었는지 확인하기 편함)
test:
  value: hell world!
  age: 10

server:
  port: 8080

# application.properties와 동시 작성이 가능하지만 주로 yml만 사용