server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
#        - id: 1st-service-get
##          uri: http://localhost:51277/
#          # ?? ??? ??? ???? ??? ??? ? ??? ??? ?? ??
#          # ??? ???? ??? ????? ?? ??? ??
#
#          # ??? ? ???? ???(?, application name? ??(??? ??? ????? ?? ?? ??? ??))
#          uri: lb://1ST-SERVICE
#          # gateway ??? ??? ?? ???? ???(??? ???)
#          predicates:
#            - Path=/first-service/**
#          # ?? ??? ? ???? ???? /first-service?? ???? ???? ?? ????? ???? ? + ?? ??
#          # ???? built in ?? + custom ??(feat. spring security) ?? ??
#          filters:
#            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=first-request, first-request-header
#            - AddResponseHeader=first-response, first-response-header
#            # first-service ??? ??? ???? ?? ????
#            # url ??? first-service? ????? ??? ????? first-service? ??? ??? -> Mapping depth? ???
#
#        - id: 2nd-service-post
#          uri: lb://2ND-SERVICE
#          predicates:
#            - Path=/second-service/**
#            - Method=POST
#          filters:
#            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
#        - id: 2nd-service-get
#          uri: lb://2ND-SERVICE
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - RewritePath=/second-service/(?<segment>.*), /$\{segment}

# ??. gateway? routes ??? ?? ??(? ??? http method ?? ??)? ?? ?? ????.

#        - id: user-service-post-user
#          uri: lb://SWCAMP-USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#            - Method=POST
#          filters:
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#
#        - id: user-service-get-user
#          uri: lb://SWCAMP-USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#            - Method=GET
#          filters:
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
#
#        - id: order-service-get
#          uri: lb://SWCAMP-ORDER-SERVICE
#          predicates:
#            - Path=/order-service/**
#            - Method=GET
#          filters:
#            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter


        - id: catdog-post-service
          uri: lb://CATDOGSHELTER
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}

        - id: CatDogShelter-user-service
          uri: lb://CATDOGSHELTER-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter


token:
  expiration_time: 43200000
  secret: "VKKCjFzrzJQE8oM69GmgavfauYLnHnQeG4k1ab/lrYtrEQMk7o0/3j8KmqM33prEOWs5IdSVhQsbKiV3UzFhHQ=="
